name: brig_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  firebase_core: ^2.18.0
  url_launcher: ^6.1.14
  flutter:
   sdk: flutter
  firebase_database: ^10.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/images/backgroundColor.png
