name: brig_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  firebase_core: ^2.18.0
  url_launcher: ^6.1.14
  flutter:
   sdk: flutter
  firebase_database: ^10.3.3
  firebase_storage: ^11.4.1
  firebase_auth: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/backgroundColor.png
    - assets/images/tornadoTransparent.png
    - assets/images/gold_tornado.png
    - assets/images/apple.png
    - assets/images/burger.png
    - assets/images/drinks.png
    - assets/images/fries.png
    - assets/images/geneva_logo.png
    - assets/images/granola.png
    - assets/images/wordBrig.png
    - assets/images/wrap.png
